Remove second `MockedEndpoint` interface
It looks like this is unused? It's breaking your exported interface, though. The following code didn't previously compile (and it looks like you intend for it to compile):

```ts
import * as mockttp from 'mockttp';

const mockServer = await mockttp.getLocal().start();
const mockedEndpoint: mockttp.MockedEndpoint = mockServer.get('/foo').thenReply(200);
```

```
error TS2719: Type 'MockedEndpoint' is not assignable to type 'MockedEndpoint'. Two different types with this name exist, but they are unrelated.
  Types of property 'getSeenRequests' are incompatible.
    Type '() => Promise<CompletedRequest[]>' is not assignable to type '() => Request[]'.
      Type 'Promise<CompletedRequest[]>' is not assignable to type 'Request[]'.
        Property 'includes' is missing in type 'Promise<CompletedRequest[]>'.
```